#!/usr/bin/env sh

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Zsh
# if the user has a .zshrc file, back it up and symlink the one in the dotfiles - but only if it's not already a symlink
if [ -f $HOME/.zshrc ] && [ ! -L $HOME/.zshrc ]; then
    mv $HOME/.zshrc $HOME/.zshrc.bak
fi

ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc


# Git
ln -sf $DOTFILES/git/gitignore_global $HOME/.gitignore_global

# copy the template to the home directory - if it exists, it will be overwritten
if [ -f $HOME/.git-template ]; then
    rm $HOME/.git-template
fi

# make the secrets directory if it doesn't exist
if [ ! -d $HOME/.dotfiles/secrets ]; then
    mkdir -p $HOME/.dotfiles/secrets
fi

# if the env files does not exist, create it in the secrets directory
if [ ! -f $HOME/.dotfiles/secrets/env ]; then
    touch $HOME/.dotfiles/secrets/env
fi

cp $DOTFILES/git/git-template $HOME/.git-template

echo "Created a global git commit template at $HOME/.git-template"
git config --global commit.template $HOME/.git-template

# Zed snippets
# symlink to snippets directory or create it if it doesn't exist
if [ ! -d $HOME/.config/zed/snippets ]; then
    mkdir -p $HOME/.config/zed/snippets
fi

ln -sf $DOTFILES/zed/snippets/* $HOME/.config/zed/snippets/
